### ISSUE TITLE
[BUG] [FCM] Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1369]
### Description

FCM was configured but fails to launch on `tmail.linagora.com` because of a failure to determine the underlying plateform.

Tested on both Chromium (108.0.5359.124 snap) and Firefox (108.0)

### Expected result

FCM should be correctly initialized

### Current behavior

Chromium:

```
 MailboxDashBoardController::_getAppVersion(): 0.5.2
 [ERROR] Unsupported operation: Platform._operatingSystem
    at Object.wrapException (https://tmail.linagora.com/main.dart.js:8770:17)
    at Object._Platform__operatingSystem (https://tmail.linagora.com/main.dart.js:17385:15)
    at Object._Platform_operatingSystem (https://tmail.linagora.com/main.dart.js:17442:16)
    at https://tmail.linagora.com/main.dart.js:319297:90
    at holder.<computed> [as $get$Platform__operatingSystem] (https://tmail.linagora.com/main.dart.js:129:21)
    at https://tmail.linagora.com/main.dart.js:319311:9
    at holder.<computed> [as $get$Platform_isAndroid] (https://tmail.linagora.com/main.dart.js:129:21)
    at https://tmail.linagora.com/main.dart.js:294235:31
    at _wrapJsFunctionForAsync_closure.$protected (https://tmail.linagora.com/main.dart.js:11541:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://tmail.linagora.com/main.dart.js:103097:12)
main.dart.js:73072 FcmReceiver::onFcmToken():exception: FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
main.dart.js:73072 [ERROR] Instance of 'NotLoadedFCMTokenException'
    at Object.wrapException (https://tmail.linagora.com/main.dart.js:8770:17)
    at https://tmail.linagora.com/main.dart.js:294507:23
    at _wrapJsFunctionForAsync_closure.$protected (https://tmail.linagora.com/main.dart.js:11541:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://tmail.linagora.com/main.dart.js:103097:12)
    at _awaitOnObject_closure0.call$2 (https://tmail.linagora.com/main.dart.js:103091:25)
    at Object._rootRunBinary (https://tmail.linagora.com/main.dart.js:12173:18)
    at StaticClosure.<anonymous> (https://tmail.linagora.com/main.dart.js:307821:16)
    at _CustomZone.runBinary$3$3 (https://tmail.linagora.com/main.dart.js:105605:39)
    at _FutureListener.handleError$1 (https://tmail.linagora.com/main.dart.js:103795:21)
    at _Future__propagateToListeners_handleError.call$0 (https://tmail.linagora.com/main.dart.js:104118:49)
```

Firefox:

```
[ERROR] BaseController::injectFCMBindings(): exception: Instance of 'NotSupportFCMException'
 [ERROR] wrapException@https://tmail.linagora.com/main.dart.js:8770:17
_Platform__operatingSystem@https://tmail.linagora.com/main.dart.js:17385:15
_Platform_operatingSystem@https://tmail.linagora.com/main.dart.js:17442:16
@https://tmail.linagora.com/main.dart.js:319297:90
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
@https://tmail.linagora.com/main.dart.js:319311:9
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
_checkLocalNotificationPermission$0/$async$_checkLocalNotificationPermission$0<@https://tmail.linagora.com/main.dart.js:294235:31
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11541:17
call$2@https://tmail.linagora.com/main.dart.js:103097:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11505:20
_checkLocalNotificationPermission$0@https://tmail.linagora.com/main.dart.js:294271:16
setUp$0/$async$setUp$0<@https://tmail.linagora.com/main.dart.js:294129:27
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11541:17
call$2@https://tmail.linagora.com/main.dart.js:103097:12
call$1@https://tmail.linagora.com/main.dart.js:103085:32
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12159:18
@https://tmail.linagora.com/main.dart.js:307818:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105600:39
call$0@https://tmail.linagora.com/main.dart.js:104100:51
_Future__propagateToListeners@https://tmail.linagora.com/main.dart.js:11855:93
_completeWithValue$1@https://tmail.linagora.com/main.dart.js:103959:9
complete$1@https://tmail.linagora.com/main.dart.js:103072:14
_asyncReturn@https://tmail.linagora.com/main.dart.js:11513:17
_initLocalNotification$0/$async$_initLocalNotification$0<@https://tmail.linagora.com/main.dart.js:294209:24
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11541:17
call$2@https://tmail.linagora.com/main.dart.js:103097:12
call$1@https://tmail.linagora.com/main.dart.js:103085:32
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12159:18
@https://tmail.linagora.com/main.dart.js:307818:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105600:39
call$0@https://tmail.linagora.com/main.dart.js:104100:51
_Future__propagateToListeners@https://tmail.linagora.com/main.dart.js:11855:93
_completeWithValue$1@https://tmail.linagora.com/main.dart.js:103959:9
call$0@https://tmail.linagora.com/main.dart.js:104036:18
_rootRun@https://tmail.linagora.com/main.dart.js:12149:16
@https://tmail.linagora.com/main.dart.js:307815:16
run$1$1@https://tmail.linagora.com/main.dart.js:105595:39
runGuarded$1@https://tmail.linagora.com/main.dart.js:105531:14
call$0@https://tmail.linagora.com/main.dart.js:105716:25
_microtaskLoop@https://tmail.linagora.com/main.dart.js:11916:24
_startMicrotaskLoop@https://tmail.linagora.com/main.dart.js:11922:11
call$1@https://tmail.linagora.com/main.dart.js:102980:9
invokeClosure@https://tmail.linagora.com/main.dart.js:8973:26
convertDartClosureToJS/$function</<@https://tmail.linagora.com/main.dart.js:8992:18
FrameRequestCallback*_requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113742:23
requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113739:19
call$0@https://tmail.linagora.com/main.dart.js:90361:26
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:91462:10
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:174150:51
scheduleFrameCallback$2$rescheduling@https://tmail.linagora.com/main.dart.js:174090:13
_ticker$_tick$1@https://tmail.linagora.com/main.dart.js:174419:59
Closure_cspForwardCall/</<@https://tmail.linagora.com/main.dart.js:9083:45
_invokeFrameCallback$3@https://tmail.linagora.com/main.dart.js:174266:18
call$2@https://tmail.linagora.com/main.dart.js:174344:12
forEach$1@https://tmail.linagora.com/main.dart.js:102303:16
forEach$1$ax@https://tmail.linagora.com/main.dart.js:76995:44
handleBeginFrame$1@https://tmail.linagora.com/main.dart.js:174217:11
_handleBeginFrame$1@https://tmail.linagora.com/main.dart.js:174187:12
Closure_cspForwardCall/</<@https://tmail.linagora.com/main.dart.js:9083:45
invoke1@https://tmail.linagora.com/main.dart.js:3193:18
call$1@https://tmail.linagora.com/main.dart.js:90377:11
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12163:16
@https://tmail.linagora.com/main.dart.js:307818:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105600:39
runUnaryGuarded$1$2@https://tmail.linagora.com/main.dart.js:105541:14
call$1@https://tmail.linagora.com/main.dart.js:105722:25
invokeClosure@https://tmail.linagora.com/main.dart.js:8973:26
convertDartClosureToJS/$function</<@https://tmail.linagora.com/main.dart.js:8992:18
FrameRequestCallback*_requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113742:23
requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113739:19
call$0@https://tmail.linagora.com/main.dart.js:90361:26
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:91462:10
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:174150:51
scheduleFrameCallback$2$rescheduling@https://tmail.linagora.com/main.dart.js:174090:13
_ticker$_tick$1@https://tmail.linagora.com/main.dart.js:174419:59
Closure_cspForwardCall/</<@https://tmail.linagora.com/main.dart.js:9083:45
_invokeFrameCallback$3@https://tmail.linagora.com/main.dart.js:174266:18
call$2@https://tmail.linagora.com/main.dart.js:174344:12
forEach$1@https://tmail.linagora.com/main.dart.js:102303:16
forEach$1$ax@https://tmail.linagora.com/main.dart.js:76995:44
handleBeginFrame$1@https://tmail.linagora.com/main.dart.js:174217:11
_handleBeginFrame$1@https://tmail.linagora.com/main.dart.js:174187:12
Closure_cspForwardCall/</<@https://tmail.linagora.com/main.dart.js:9083:45
invoke1@https://tmail.linagora.com/main.dart.js:3193:18
call$1@https://tmail.linagora.com/main.dart.js:90377:11
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12163:16
@https://tmail.linagora.com/main.dart.js:307818:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105600:39
runUnaryGuarded$1$2@https://tmail.linagora.com/main.dart.js:105541:14
call$1@https://tmail.linagora.com/main.dart.js:105722:25
invokeClosure@https://tmail.linagora.com/main.dart.js:8973:26
convertDartClosureToJS/$function</<@https://tmail.linagora.com/main.dart.js:8992:18
FrameRequestCallback*_requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113742:23
requestAnimationFrame$1@https://tmail.linagora.com/main.dart.js:113739:19
call$0@https://tmail.linagora.com/main.dart.js:90361:26
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:91462:10
scheduleFrame$0@https://tmail.linagora.com/main.dart.js:174150:51
scheduleFrameCallback$2$rescheduling@https://tmail.linagora.com/main.dart.js:174090:13
```

#### Reproduction Steps

Run 0.5.2 on web with FCM configured.

### Acceptance criteria

FCM correctly initializes for WEB

### Context

Tested on both Chromium (108.0.5359.124 snap) and Firefox (108.0)

**Comment by chibenwa** [comment]
On v0.5.1, Chromium

```
[ERROR] BaseController::injectFCMBindings(): exception: Unsupported operation: Platform._operatingSystem
main.dart.js:73057 _handleOpenAppByNotification(): isOpenAppByNotification: false
main.dart.js:73057 MailboxDashBoardController::_registerPendingEmailAddress(): null
main.dart.js:73057 MailboxDashBoardController::_registerPendingFileInfo(): 0
main.dart.js:73057 MailboxDashBoardController::onData():success LoadingGetAllVacation
main.dart.js:73057 [ERROR] LocalNotificationManager::setUp(): ERROR: Unsupported operation: Platform._operatingSystem
main.dart.js:73057 MailboxDashBoardController::dispatchRoute(): DashboardRoutes.thread
main.dart.js:73057 [ERROR] Unsupported operation: Platform._operatingSystem
    at Object.wrapException (https://tmail.linagora.com/main.dart.js:8734:17)
    at Object._Platform__operatingSystem (https://tmail.linagora.com/main.dart.js:17349:15)
    at Object._Platform_operatingSystem (https://tmail.linagora.com/main.dart.js:17406:16)
    at https://tmail.linagora.com/main.dart.js:319282:90
    at holder.<computed> [as $get$Platform__operatingSystem] (https://tmail.linagora.com/main.dart.js:129:21)
    at https://tmail.linagora.com/main.dart.js:319296:9
    at holder.<computed> [as $get$Platform_isAndroid] (https://tmail.linagora.com/main.dart.js:129:21)
    at https://tmail.linagora.com/main.dart.js:294215:31
    at _wrapJsFunctionForAsync_closure.$protected (https://tmail.linagora.com/main.dart.js:11505:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://tmail.linagora.com/main.dart.js:102826:12)
```

Same outcome...

**Comment by chibenwa** [comment]
On v0.5.1, Firefox

```
[ERROR] BaseController::injectFCMBindings(): exception: Unsupported operation: Platform._operatingSystem main.dart.js:73057:17
_handleOpenAppByNotification(): isOpenAppByNotification: false main.dart.js:73057:17
MailboxDashBoardController::_registerPendingEmailAddress(): null main.dart.js:73057:17
MailboxDashBoardController::_registerPendingFileInfo(): 0 main.dart.js:73057:17
MailboxDashBoardController::onData():success LoadingGetAllVacation main.dart.js:73057:17
[ERROR] LocalNotificationManager::setUp(): ERROR: Unsupported operation: Platform._operatingSystem main.dart.js:73057:17
MailboxDashBoardController::dispatchRoute(): DashboardRoutes.thread main.dart.js:73057:17
[ERROR] wrapException@https://tmail.linagora.com/main.dart.js:8734:17
_Platform__operatingSystem@https://tmail.linagora.com/main.dart.js:17349:15
_Platform_operatingSystem@https://tmail.linagora.com/main.dart.js:17406:16
@https://tmail.linagora.com/main.dart.js:319282:90
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
@https://tmail.linagora.com/main.dart.js:319296:9
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
_checkLocalNotificationPermission$0/$async$_checkLocalNotificationPermission$0<@https://tmail.linagora.com/main.dart.js:294215:31
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
_checkLocalNotificationPermission$0@https://tmail.linagora.com/main.dart.js:294251:16
setUp$0/$async$setUp$0<@https://tmail.linagora.com/main.dart.js:294109:27
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
call$1@https://tmail.linagora.com/main.dart.js:102814:32
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12123:18
@https://tmail.linagora.com/main.dart.js:307807:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105329:39
call$0@https://tmail.linagora.com/main.dart.js:103829:51
_Future__propagateToListeners@https://tmail.linagora.com/main.dart.js:11819:93
_completeWithValue$1@https://tmail.linagora.com/main.dart.js:103688:9
complete$1@https://tmail.linagora.com/main.dart.js:102801:14
_asyncReturn@https://tmail.linagora.com/main.dart.js:11477:17
_initLocalNotification$0/$async$_initLocalNotification$0<@https://tmail.linagora.com/main.dart.js:294189:24
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
call$1@https://tmail.linagora.com/main.dart.js:102814:32
_rootRunUnary@https://tmail.linagora.com/main.dart.js:12123:18
@https://tmail.linagora.com/main.dart.js:307807:16
runUnary$2$2@https://tmail.linagora.com/main.dart.js:105329:39
call$0@https://tmail.linagora.com/main.dart.js:103829:51
_Future__propagateToListeners@https://tmail.linagora.com/main.dart.js:11819:93
_completeWithValue$1@https://tmail.linagora.com/main.dart.js:103688:9
call$0@https://tmail.linagora.com/main.dart.js:103765:18
_rootRun@https://tmail.linagora.com/main.dart.js:12113:16
@https://tmail.linagora.com/main.dart.js:307804:16
run$1$1@https://tmail.linagora.com/main.dart.js:105324:39
runGuarded$1@https://tmail.linagora.com/main.dart.js:105260:14
call$0@https://tmail.linagora.com/main.dart.js:105445:25
_microtaskLoop@https://tmail.linagora.com/main.dart.js:11880:24
_startMicrotaskLoop@https://tmail.linagora.com/main.dart.js:11886:11
call$1@https://tmail.linagora.com/main.dart.js:102709:9
invokeClosure@https://tmail.linagora.com/main.dart.js:8937:26
convertDartClosureToJS/$function</<@https://tmail.linagora.com/main.dart.js:8956:18
MutationCallback*_AsyncRun__initializeScheduleImmediate@https://tmail.linagora.com/main.dart.js:11432:9
@https://tmail.linagora.com/main.dart.js:319231:110
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
_scheduleAsyncCallback@https://tmail.linagora.com/main.dart.js:11900:13
_rootScheduleMicrotask@https://tmail.linagora.com/main.dart.js:12166:9
scheduleMicrotask$1@https://tmail.linagora.com/main.dart.js:105623:9
_asyncCompleteWithValue$1@https://tmail.linagora.com/main.dart.js:103704:18
_asyncComplete$1@https://tmail.linagora.com/main.dart.js:103700:12
Future_Future$value@https://tmail.linagora.com/main.dart.js:11648:10
call$0@https://tmail.linagora.com/main.dart.js:100639:16
run$1$1@https://tmail.linagora.com/main.dart.js:105597:18
@https://tmail.linagora.com/main.dart.js:319176:72
lazyFinal/holder[getterName]@https://tmail.linagora.com/main.dart.js:129:21
cancel$0@https://tmail.linagora.com/main.dart.js:113940:16
cancel$0$z@https://tmail.linagora.com/main.dart.js:76821:43
call$1@https://tmail.linagora.com/main.dart.js:81036:9
call$1@https://tmail.linagora.com/main.dart.js:113988:26
invokeClosure@https://tmail.linagora.com/main.dart.js:8937:26
convertDartClosureToJS/$function</<@https://tmail.linagora.com/main.dart.js:8956:18
EventListener.handleEvent*_addEventListener$3@https://tmail.linagora.com/main.dart.js:112147:23
addEventListener$3@https://tmail.linagora.com/main.dart.js:112134:14
addEventListener$3$x@https://tmail.linagora.com/main.dart.js:76776:43
_tryResume$0@https://tmail.linagora.com/main.dart.js:113973:11
_EventStreamSubscription$@https://tmail.linagora.com/main.dart.js:16594:10
_downloadCanvasKitJs@https://tmail.linagora.com/main.dart.js:930:49
downloadCanvasKit/$async$downloadCanvasKit<@https://tmail.linagora.com/main.dart.js:904:38
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
downloadCanvasKit@https://tmail.linagora.com/main.dart.js:918:16
initializeCanvasKit/$async$initializeCanvasKit<@https://tmail.linagora.com/main.dart.js:877:38
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
initializeCanvasKit@https://tmail.linagora.com/main.dart.js:890:16
initializeEngineServices$body/$async$initializeEngineServices<@https://tmail.linagora.com/main.dart.js:2942:38
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
initializeEngineServices$body@https://tmail.linagora.com/main.dart.js:2976:16
initializeEngineServices@https://tmail.linagora.com/main.dart.js:2910:16
call$0/$async$call$0<@https://tmail.linagora.com/main.dart.js:116194:38
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
call$0@https://tmail.linagora.com/main.dart.js:116201:16
autoStart$0/$async$autoStart$0<@https://tmail.linagora.com/main.dart.js:77465:60
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
autoStart$0@https://tmail.linagora.com/main.dart.js:77476:16
webOnlyWarmupEngine/$async$webOnlyWarmupEngine<@https://tmail.linagora.com/main.dart.js:18018:46
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
webOnlyWarmupEngine@https://tmail.linagora.com/main.dart.js:18036:16
main/$async$main<@https://tmail.linagora.com/main.dart.js:73032:38
_wrapJsFunctionForAsync/$protected</<@https://tmail.linagora.com/main.dart.js:11505:17
call$2@https://tmail.linagora.com/main.dart.js:102826:12
_asyncStartSync@https://tmail.linagora.com/main.dart.js:11469:20
main@https://tmail.linagora.com/main.dart.js:73039:16
@https://tmail.linagora.com/main.dart.js:320014:15
@https://tmail.linagora.com/main.dart.js:319997:15
dartProgram@https://tmail.linagora.com/main.dart.js:320008:5
@https://tmail.linagora.com/main.dart.js:320016:3
main.dart.js:73057:17
```
