### ISSUE TITLE
Composer crash

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1596]
### Description

After editing an email with for some time, I some time get a crash

 -> Some time I get a white page
 
 -> Some time clicking the send button yields no action

**And my input is lost!**

### Expected result

Smoothly edit my email.

### Current behavior

https://user-images.githubusercontent.com/6928740/224881547-a2d238a1-e6cf-4340-905f-1b5ce96e4d17.mp4

#### Reproduction Steps

Copy and paste?

Line breaks?

Reply to an email with inlined image

### Context

v 0.7.1  on tmail.linagora.com

$ chromium -version
Chromium 111.0.5563.64 snap

### Additional information

```
Uncaught RangeError: Invalid string length
    at Interceptor.$add (main.dart.js:101885:23)
    at Object.log (main.dart.js:20167:42)
    at Object.logError (main.dart.js:20171:16)
    at initLogger_closure0.call$2 (main.dart.js:123321:9)
    at _RootZone.runBinary$3$3 (main.dart.js:107428:18)
    at runZonedGuarded_closure.call$5 (main.dart.js:107500:25)
    at _CustomZone._processUncaughtError$3 (main.dart.js:107055:17)
    at _CustomZone.runUnaryGuarded$1$2 (main.dart.js:107095:14)
    at Object.invoke1 (main.dart.js:3195:14)
    at PointerBinding._onPointerData$1 (main.dart.js:93274:9)
wrapException @ main.dart.js:8774
Error__throw @ main.dart.js:14217
Error_throwWithStackTrace @ main.dart.js:14720
call$0 @ main.dart.js:107289
_microtaskLoop @ main.dart.js:11920
_startMicrotaskLoop @ main.dart.js:11926
call$1 @ main.dart.js:104524
invokeClosure @ main.dart.js:8977
(anonymous) @ main.dart.js:8996
childList (async)
call$1 @ main.dart.js:104534
_scheduleAsyncCallback @ main.dart.js:11940
_schedulePriorityAsyncCallback @ main.dart.js:11948
_rootHandleError @ main.dart.js:12143
_processUncaughtError$3 @ main.dart.js:107044
call$5 @ main.dart.js:107508
_processUncaughtError$3 @ main.dart.js:107055
runUnaryGuarded$1$2 @ main.dart.js:107095
invoke1 @ main.dart.js:3195
_onPointerData$1 @ main.dart.js:93274
(anonymous) @ main.dart.js:9087
call$1 @ main.dart.js:93557
call$1 @ main.dart.js:93516
call$1 @ main.dart.js:93299
invokeClosure @ main.dart.js:8977
(anonymous) @ main.dart.js:8996
```

Just before that I get this log:

[input.txt](https://github.com/linagora/tmail-flutter/files/10963773/input.txt)

then:

```
RichTextWebController::onEditorSettingsChange():
main.dart.js:74498 RichTextWebController::onEditorSettingsChange(): []
```

**Comment by chibenwa** [comment]
CC @QuangHoang1210  is this a duplicate?

Are there related issues?
