### ISSUE TITLE
Message composer windows Send Button not work if left open too long

### ISSUE THREAD

**Issue by ducnm0711** [linagora/tmail-flutter#1605]
### Description

Open composer - keep it open for a while (probably longer than 15mins) - Hit "Send" - Mail not delivered
![image](https://user-images.githubusercontent.com/59911858/225270243-adead15b-566b-4127-a622-edc7955543f2.png)

### Context
OS: Windows
Browser: Chrome

**Comment by chibenwa** [comment]
:+1: I have a similar issue.

Anything in the browser console ?

**Comment by dab246** [comment]
I cannot reproduce it.  we need more information to investigate it.

**Comment by chibenwa** [comment]
Randomly gets this, generally when I take time composing a long mail with inlined attachments.

**Comment by chibenwa** [comment]
https://user-images.githubusercontent.com/6928740/225377937-c3114e61-a71c-4b9c-8301-40949c43a026.mp4

Caught on camera!

```
Uncaught RangeError: Invalid string length
    at Interceptor.$add (/main.dart.js:101885:23)
    at Object.log (/main.dart.js:20167:42)
    at Object.logError (/main.dart.js:20171:16)
    at initLogger_closure0.call$2 (/main.dart.js:123321:9)
    at _RootZone.runBinary$3$3 (/main.dart.js:107428:18)
    at runZonedGuarded_closure.call$5 (/main.dart.js:107500:25)
    at _CustomZone._processUncaughtError$3 (/main.dart.js:107055:17)
    at _CustomZone.handleUncaughtError$2 (/main.dart.js:107135:12)
    at Object._Future__propagateToListeners (/main.dart.js:11815:22)
    at _Future._completeError$2 (/main.dart.js:105508:9)
wrapException @ /main.dart.js:8774
Error__throw @ /main.dart.js:14217
Error_throwWithStackTrace @ /main.dart.js:14720
call$0 @ /main.dart.js:107289
_microtaskLoop @ /main.dart.js:11920
_startMicrotaskLoop @ /main.dart.js:11926
call$1 @ /main.dart.js:104524
invokeClosure @ /main.dart.js:8977
(anonymous) @ /main.dart.js:8996
childList (async)
call$1 @ /main.dart.js:104534
_scheduleAsyncCallback @ /main.dart.js:11940
_rootScheduleMicrotask @ /main.dart.js:12206
scheduleMicrotask$1 @ /main.dart.js:107184
_asyncCompleteWithValue$1 @ /main.dart.js:105519
_asyncComplete$1 @ /main.dart.js:105515
complete$1 @ /main.dart.js:105304
complete$0 @ /main.dart.js:105307
_ticker$_complete$0 @ /main.dart.js:176567
TickerFuture$complete @ /main.dart.js:37419
_animateToInternal$3$curve$duration @ /main.dart.js:131439
_animateToInternal$1 @ /main.dart.js:131444
forward$1$from @ /main.dart.js:131397
forward$0 @ /main.dart.js:131400
confirm$0 @ /main.dart.js:144400
_handleTap$0 @ /main.dart.js:144895
(anonymous) @ /main.dart.js:9081
invokeCallback$1$3$debugReport @ /main.dart.js:138519
invokeCallback$2 @ /main.dart.js:138529
handleTapUp$2$down$up @ /main.dart.js:138860
_checkUp$0 @ /main.dart.js:138794
handlePrimaryPointer$1 @ /main.dart.js:138723
handleEvent$1 @ /main.dart.js:138643
(anonymous) @ /main.dart.js:9087
_dispatch$3 @ /main.dart.js:138431
call$2 @ /main.dart.js:138463
forEach$1 @ /main.dart.js:103847
_dispatchEventToRoutes$3 @ /main.dart.js:138451
route$1 @ /main.dart.js:138447
handleEvent$2 @ /main.dart.js:136901
dispatchEvent$2 @ /main.dart.js:136888
dispatchEvent$2 @ /main.dart.js:184266
_handlePointerEventImmediately$1 @ /main.dart.js:136867
handlePointerEvent$1 @ /main.dart.js:136848
_flushPointerEventQueue$0 @ /main.dart.js:136844
_handlePointerDataPacket$1 @ /main.dart.js:136834
(anonymous) @ /main.dart.js:9087
_rootRunUnary @ /main.dart.js:12167
(anonymous) @ /main.dart.js:315539
runUnary$2$2 @ /main.dart.js:107150
runUnaryGuarded$1$2 @ /main.dart.js:107091
invoke1 @ /main.dart.js:3195
_onPointerData$1 @ /main.dart.js:93274
(anonymous) @ /main.dart.js:9087
call$1 @ /main.dart.js:93573
call$1 @ /main.dart.js:93516
call$1 @ /main.dart.js:93299
invokeClosure @ /main.dart.js:8977
(anonymous) @ /main.dart.js:8996
```

**Comment by dab246** [comment]
Same #1596
