### ISSUE TITLE
[Compose] User has been crashed when trying to click Bcc at Compose

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1629]
OS: Window
Browser: Chrome/safari/firefox
Device: Laptop
TMail version: 0.7.4 (preprod)

*Precondition: User already login successfully

*Reproduce Step:
1, User click to view details of an email
2, User click fowards 
3, User click bcc

Actual: App crashed
Expected: User can select Bcc and Tmail app smoothly

https://user-images.githubusercontent.com/124866146/226413954-1893736c-b55e-4d3f-aa3d-273a3377adac.mp4

**Comment by QuangHoang1210** [comment]
```
(index):85 Loading app from service worker.
main.dart.js:80634 Got object store box in database encryptionkeycache.
main.dart.js:80634 Got object store box in database emailcache.
main.dart.js:80634 Got object store box in database recentsearchcache.
main.dart.js:80634 Got object store box in database accountcache.
main.dart.js:80634 Got object store box in database tokenoidccache.
main.dart.js:80634 Got object store box in database mailboxcache.
main.dart.js:80634 Got object store box in database statecache.
VM115 about:srcdoc:28 done
DevTools failed to load source map: Could not load content for https://tmail.upn.integration-open-paas.org/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.dart.js:80634 NoSuchMethodError: method not found: 'endRecording$0' on null
main.dart.js:80634     at HtmlViewEmbedder.submitFrame$0 (https://tmail.upn.integration-open-paas.org/main.dart.js:87453:79)
main.dart.js:80634     at Rasterizer.draw$1 (https://tmail.upn.integration-open-paas.org/main.dart.js:89874:44)
main.dart.js:80634     at CanvasKitRenderer.renderScene$1 (https://tmail.upn.integration-open-paas.org/main.dart.js:90128:29)
main.dart.js:80634     at RenderView.compositeFrame$0 (https://tmail.upn.integration-open-paas.org/main.dart.js:189845:12)
main.dart.js:80634     at WidgetsFlutterBinding.drawFrame$0 (https://tmail.upn.integration-open-paas.org/main.dart.js:177308:76)
main.dart.js:80634     at WidgetsFlutterBinding.drawFrame$0 (https://tmail.upn.integration-open-paas.org/main.dart.js:200243:15)
main.dart.js:80634     at WidgetsFlutterBinding._handlePersistentFrameCallback$1 (https://tmail.upn.integration-open-paas.org/main.dart.js:177289:12)
main.dart.js:80634     at tear_off.<anonymous> (https://tmail.upn.integration-open-paas.org/main.dart.js:9659:45)
main.dart.js:80634     at WidgetsFlutterBinding._invokeFrameCallback$3 (https://tmail.upn.integration-open-paas.org/main.dart.js:191623:18)
main.dart.js:80634     at WidgetsFlutterBinding._invokeFrameCallback$2 (https://tmail.upn.integration-open-paas.org/main.dart.js:191632:19)
2main.dart.js:80634 Another exception was thrown: Instance of 'ErrorSummary'
main.dart.js:18365 Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once. You may experience incorrect rendering.
callMethod @ main.dart.js:18365
call$1 @ main.dart.js:91417
prerollCompositeEmbeddedView$2 @ main.dart.js:87201
preroll$2 @ main.dart.js:89202
prerollChildren$2 @ main.dart.js:88962
preroll$2 @ main.dart.js:89132
prerollChildren$2 @ main.dart.js:88962
preroll$2 @ main.dart.js:89065
prerollChildren$2 @ main.dart.js:88962
preroll$2 @ main.dart.js:89132
prerollChildren$2 @ main.dart.js:88962
preroll$2 @ main.dart.js:89132
prerollChildren$2 @ main.dart.js:88962
preroll$2 @ main.dart.js:89132
prerollChildren$2 @ main.dart.js:88962
call$0 @ main.dart.js:89342
timeAction @ main.dart.js:3194
raster$2$ignoreRasterCache @ main.dart.js:89334
draw$1 @ main.dart.js:89868
renderScene$1 @ main.dart.js:90128
compositeFrame$0 @ main.dart.js:189845
drawFrame$0 @ main.dart.js:177308
drawFrame$0 @ main.dart.js:200243
_handlePersistentFrameCallback$1 @ main.dart.js:177289
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
_invokeFrameCallback$2 @ main.dart.js:191632
handleDrawFrame$0 @ main.dart.js:191592
_handleDrawFrame$0 @ main.dart.js:191533
(anonymous) @ main.dart.js:9653
_rootRun @ main.dart.js:12883
(anonymous) @ main.dart.js:346518
run$1$1 @ main.dart.js:114804
runGuarded$1 @ main.dart.js:114743
invoke @ main.dart.js:3116
call$1 @ main.dart.js:99043
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
scheduleFrameCallback$2$rescheduling @ main.dart.js:191427
_ticker$_tick$1 @ main.dart.js:191773
(anonymous) @ main.dart.js:9659
_invokeFrameCallback$3 @ main.dart.js:191623
call$2 @ main.dart.js:191701
forEach$1 @ main.dart.js:111255
forEach$1$ax @ main.dart.js:85130
handleBeginFrame$1 @ main.dart.js:191554
_handleBeginFrame$1 @ main.dart.js:191524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
call$1 @ main.dart.js:99039
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
requestAnimationFrame (async)
callMethod @ main.dart.js:18365
call$0 @ main.dart.js:99023
scheduleFrame$0 @ main.dart.js:100169
scheduleFrame$0 @ main.dart.js:191487
ensureVisualUpdate$0 @ main.dart.js:191470
_handleBuildScheduled$0 @ main.dart.js:199584
(anonymous) @ main.dart.js:9653
scheduleBuildFor$1 @ main.dart.js:206226
markNeedsBuild$0 @ main.dart.js:206772
setState$1 @ main.dart.js:206142
handleStatesControllerChange$0 @ main.dart.js:156194
(anonymous) @ main.dart.js:9653
notifyListeners$0 @ main.dart.js:146101
update$2 @ main.dart.js:160811
_startNewSplash$2$context$details @ main.dart.js:156516
_startNewSplash$1$details @ main.dart.js:156528
handleTapDown$1 @ main.dart.js:156497
(anonymous) @ main.dart.js:9659
call$0 @ main.dart.js:149792
invokeCallback$1$3$debugReport @ main.dart.js:149422
invokeCallback$2 @ main.dart.js:149432
handleTapDown$1$down @ main.dart.js:149743
_tap$_checkDown$0 @ main.dart.js:149686
acceptGesture$1 @ main.dart.js:149663
_resolveByDefault$2 @ main.dart.js:147474
call$0 @ main.dart.js:147495
_rootRun @ main.dart.js:12879
(anonymous) @ main.dart.js:346518
run$1$1 @ main.dart.js:114804
runGuarded$1 @ main.dart.js:114743
call$0 @ main.dart.js:114925
_rootRun @ main.dart.js:12883
(anonymous) @ main.dart.js:346518
run$1$1 @ main.dart.js:114804
runGuarded$1 @ main.dart.js:114743
call$0 @ main.dart.js:114925
_microtaskLoop @ main.dart.js:12658
_startMicrotaskLoop @ main.dart.js:12664
call$1 @ main.dart.js:112092
invokeClosure @ main.dart.js:9549
(anonymous) @ main.dart.js:9568
childList (async)
call$1 @ main.dart.js:112102
_scheduleAsyncCallback @ main.dart.js:12678
_rootScheduleMicrotask @ main.dart.js:12936
scheduleMicrotask$1 @ main.dart.js:114843
scheduleMicrotask @ main.dart.js:12719
_tryToResolveArena$2 @ main.dart.js:147460
close$1 @ main.dart.js:147408
handleEvent$2 @ main.dart.js:147595
dispatchEvent$2 @ main.dart.js:147580
dispatchEvent$2 @ main.dart.js:200150
_handlePointerEventImmediately$1 @ main.dart.js:147559
handlePointerEvent$1 @ main.dart.js:147538
_flushPointerEventQueue$0 @ main.dart.js:147534
_handlePointerDataPacket$1 @ main.dart.js:147524
(anonymous) @ main.dart.js:9659
_rootRunUnary @ main.dart.js:12897
(anonymous) @ main.dart.js:346521
runUnary$2$2 @ main.dart.js:114809
runUnaryGuarded$1$2 @ main.dart.js:114753
invoke1 @ main.dart.js:3124
_onPointerData$1 @ main.dart.js:100455
(anonymous) @ main.dart.js:9659
call$1 @ main.dart.js:100780
call$1 @ main.dart.js:100760
call$1 @ main.dart.js:100488
call$1 @ main.dart.js:100466
Primitives_applyFunction @ main.dart.js:9231
Function_apply @ main.dart.js:14833
_callDartFunctionFast @ main.dart.js:18317
(anonymous) @ main.dart.js:18309
2main.dart.js:80634 Another exception was thrown: Instance of 'ErrorSummary'
VM120 about:srcdoc:28 done
14main.dart.js:80634 Another exception was thrown: Instance of 'ErrorSummary'
DevTools failed to load source map: Could not load content for https://tmail.upn.integration-open-paas.org/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
277main.dart.js:80634 Another exception was thrown: Instance of 'ErrorSummary'
```
