### ISSUE TITLE
Email Reply Crash in Android 12

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2817]
### Reproduce:
- try to reply email sometimes
- Change identity sometimes
- Sent
- Observe: toast is not fully show (only blur blur)
- Then crashed

**Comment by hoangdat** [comment]
- added crashlytic to get more log to debug

**Comment by hoangdat** [comment]
<details>
<summary>App crashed</summary>

```
024-05-20 13:53:21.198                                                              I  [TwakeMail] EditorViewMixin::getEmailContentQuotedAsHtml:headerEmailQuoted: On May 20, 2024 1:32 PM, from Dat Pham <dphamhoang@linagora.com>
2024-05-20 13:53:21.216 PerfShielderService     system_server                        D  com.linagora.android.teammail|com.linagora.android.teammail/com.linagora.android.tmail.MainActivity|1820|689693619220709|55|0|48
2024-05-20 13:53:21.216 MiuiPerfServiceClient   com.miui.daemon                      W  interceptAndQueuing:31688|com.linagora.android.teammail|1820|55|689693619220709|Slow main thread|48
2024-05-20 13:53:21.459 flutter                 com.linagora.android.teammail        E  [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
                                                                                        	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1082)
                                                                                        	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1152)
                                                                                        	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1461)
                                                                                        	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                        	at android.os.MessageQueue.next(MessageQueue.java:340)
                                                                                        	at android.os.Looper.loopOnce(Looper.java:168)
                                                                                        	at android.os.Looper.loop(Looper.java:299)
                                                                                        	at android.app.ActivityThread.main(ActivityThread.java:8280)
                                                                                        	at java.lang.reflect.Method.invoke(Native Method)
                                                                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
2024-05-20 13:53:21.459                                                              A  [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1694)] Check failed: fml::jni::CheckException(env). 
2024-05-20 13:53:21.662                                                              I  *** Response ***
2024-05-20 13:53:21.664                                                              I  uri: https://jmap.linagora.com/oidc/jmap
2024-05-20 13:53:21.664                                                              I  statusCode: 200
2024-05-20 13:53:21.664                                                              I  headers:
2024-05-20 13:53:21.664                                                              I   access-control-allow-headers: Content-Type, Authorization, Accept
2024-05-20 13:53:21.664                                                              I   connection: keep-alive
2024-05-20 13:53:21.664                                                              I   date: Mon, 20 May 2024 06:53:21 GMT
2024-05-20 13:53:21.664                                                              I   transfer-encoding: chunked
2024-05-20 13:53:21.664                                                              I   access-control-allow-origin: *
2024-05-20 13:53:21.664                                                              I   content-encoding: gzip
2024-05-20 13:53:21.664                                                              I   access-control-allow-methods: GET, POST, DELETE, PUT
2024-05-20 13:53:21.665                                                              I   access-control-max-age: 86400
2024-05-20 13:53:21.665                                                              I   content-type: application/json
2024-05-20 13:53:21.665                                                              I   server: nginx
2024-05-20 13:53:21.665                                                              I  
2024-05-20 13:53:21.668                                                              I  [TwakeMail] MailboxAPI::getChanges:resultUpdated: {accountId: 94db052675894262fb8644f9517aaf25e8246c5c2eae08b34da40b748f30ec0b, state: a5166df0-1675-11ef-998c-75270c45f077, list: [Mailbox(MailboxId(Id(6add3d00-ef44-11ea-8665-3109e4489b2e)), null, null, null, null, TotalEmails(UnsignedInt(52742)), UnreadEmails(UnsignedInt(40)), TotalThreads(UnsignedInt(52742)), UnreadThreads(UnsignedInt(40)), null, null, null, null), Mailbox(MailboxId(Id(e67f6800-ef46-11ea-8665-3109e4489b2e)), null, null, null, null, TotalEmails(UnsignedInt(1141)), UnreadEmails(UnsignedInt(1)), TotalThreads(UnsignedInt(1141)), UnreadThreads(UnsignedInt(1)), null, null, null, null), Mailbox(MailboxId(Id(df4a3180-f26d-11ea-8a42-05b621cb7a62)), null, null, null, null, TotalEmails(UnsignedInt(7)), UnreadEmails(UnsignedInt(4)), TotalThreads(UnsignedInt(7)), UnreadThreads(UnsignedInt(4)), null, null, null, null)], notFound: []}
2024-05-20 13:53:21.670                                                              I  [TwakeMail] MailboxRepositoryImpl::_combineMailboxCache:mailboxUpdatedList: [Mailbox(MailboxId(Id(6add3d00-ef44-11ea-8665-3109e4489b2e)), null, null, null, null, TotalEmails(UnsignedInt(52742)), UnreadEmails(UnsignedInt(40)), TotalThreads(UnsignedInt(52742)), UnreadThreads(UnsignedInt(40)), null, null, null, null), Mailbox(MailboxId(Id(e67f6800-ef46-11ea-8665-3109e4489b2e)), null, null, null, null, TotalEmails(UnsignedInt(1141)), UnreadEmails(UnsignedInt(1)), TotalThreads(UnsignedInt(1141)), UnreadThreads(UnsignedInt(1)), null, null, null, null), Mailbox(MailboxId(Id(df4a3180-f26d-11ea-8a42-05b621cb7a62)), null, null, null, null, TotalEmails(UnsignedInt(7)), UnreadEmails(UnsignedInt(4)), TotalThreads(UnsignedInt(7)), UnreadThreads(UnsignedInt(4)), null, null, null, null)]
2024-05-20 13:53:21.672                                                              I  [TwakeMail] MailboxRepositoryImpl::_combineMailboxCache:newMailboxUpdatedList: 3
2024-05-20 13:53:21.679                                                              I  [TwakeMail] HiveCacheClient::getListByNestedKey:listItem: 52
2024-05-20 13:53:21.682                                                              I  [TwakeMail] BaseController::handleSuccessViewState(): RefreshChangesAllMailboxSuccess
2024-05-20 13:53:21.684                                                              I  [TwakeMail] MailboxController::_handleRefreshChangesAllMailboxSuccess:currentMailboxState: State(a5166df0-1675-11ef-998c-75270c45f077)
2024-05-20 13:53:21.692                                                              I  [TwakeMail] BaseMailboxController::syncAllMailboxWithDisplayName
2024-05-20 13:53:21.696                                                              I  [TwakeMail] MailboxDashBoardController::setOutboxMailbox(): PresentationMailbox(MailboxId(Id(df4a3180-f26d-11ea-8a42-05b621cb7a62)), MailboxName(Outbox), null, Role(outbox), SortOrder(UnsignedInt(50)), TotalEmails(UnsignedInt(7)), UnreadEmails(UnsignedInt(4)), TotalThreads(UnsignedInt(7)), UnreadThreads(UnsignedInt(4)), MailboxRights(true, true, true, true, true, true, true, true, true), IsSubscribed(true), SelectMode.INACTIVE, null, MailboxState.activated, Namespace(Personal), Outbox)
2024-05-20 13:53:21.698                                                              I  [TwakeMail] BaseController::handleSuccessViewState(): GetSpamMailboxCachedLoading
2024-05-20 13:53:21.700                                                              I  [TwakeMail] LocalSpamReportManager::getLastTimeDismissedSpamReported:timeStamp: 0
2024-05-20 13:53:21.702                                                              I  [TwakeMail] GetSpamMailboxCachedInteractor::_compareSpamReportTime:lastTimeDismissedSpamReported: 1970-01-01 08:00:00.000 | currentTime: 476718:53:21.701031
2024-05-20 13:53:21.706                                                              I  [TwakeMail] HiveCacheClient::getListByNestedKey:listItem: 52
2024-05-20 13:53:21.708                                                              I  [TwakeMail] [ERROR] BaseController::_performFilterExceptionInError(): null
2024-05-20 13:53:21.709                                                              I  [TwakeMail] [ERROR] BaseController::onData:exception: null
2024-05-20 13:53:21.711                                                              I  [TwakeMail] [ERROR] BaseController::handleFailureViewState(): InvalidSpamReportCondition
2024-05-20 13:53:21.792 MIUIInput               system_server                        D  [MotionEvent] publisher action=0x0, 689694735, channel 'ac10709 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity (server)'
2024-05-20 13:53:21.889                                                              D  [MotionEvent] publisher action=0x1, 689694834, channel 'ac10709 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity (server)'
2024-05-20 13:53:22.100 libPowerHal             ven...hardware.mtkpower@1.0-service  I  [perfNotifyAppState] pack:com.linagora.android.teammail, act:com.linagora.android.tmail.MainActivity, state:5, pid:31688, uid:10490, fps:-1
2024-05-20 13:53:22.257 MIUIInput               system_server                        D  [MotionEvent] publisher action=0x0, 689695201, channel 'ac10709 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity (server)'
2024-05-20 13:53:22.355                                                              D  [MotionEvent] publisher action=0x1, 689695300, channel 'ac10709 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity (server)'
2024-05-20 13:53:22.572 libc                    com.linagora.android.teammail        A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 31688 (ndroid.teammail), pid 31688 (ndroid.teammail)
2024-05-20 13:53:23.931 DEBUG                   crash_dump64                         A  Cmdline: com.linagora.android.teammail
2024-05-20 13:53:23.931                                                              A  pid: 31688, tid: 31688, name: ndroid.teammail  >>> com.linagora.android.teammail <<<
2024-05-20 13:53:23.932                                                              A        #01 pc 0000000001b97f50  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #02 pc 0000000001bc1e70  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #03 pc 0000000001ba6f04  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #04 pc 0000000002337788  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #05 pc 0000000001fdccb8  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #06 pc 0000000001fdbac4  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.932                                                              A        #07 pc 0000000001fdc214  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.933                                                              A        #08 pc 0000000001fdd3f4  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.933                                                              A        #09 pc 0000000001fdbe40  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.933                                                              A        #10 pc 0000000001fdbc00  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.933                                                              A        #11 pc 0000000001bc2a28  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:23.933                                                              A        #12 pc 0000000001bc8500  /data/app/~~h3Jxsz8Dhwn-lxlObLVpzg==/com.linagora.android.teammail-PLg25-UwaHrNhRDSUC3FTA==/lib/arm64/libflutter.so (BuildId: 9359aeb807626c855bf93aec5bc5cd83b4c0e5e9)
2024-05-20 13:53:24.078 PowerHalWrapper         system_server                        I  <NotifyAppCrash> pack:com.linagora.android.teammail ,pid:com.linagora.android.teammail == myPid:1672 
2024-05-20 13:53:24.088 ActivityTaskManager                                          W    Force finishing activity com.linagora.android.teammail/com.linagora.android.tmail.MainActivity
2024-05-20 13:53:24.108 SurfaceFlinger          surfaceflinger                       I  operator()(), mtkRenderCntDebug 1672, screenshot (Background for SurfaceView[com.linagora.android.teammail/com.linagora.android.tmail.MainActivity]#0)
2024-05-20 13:53:24.109                                                              I  operator()(), mtkRenderCntDebug 1672, screenshot (SurfaceView[com.linagora.android.teammail/com.linagora.android.tmail.MainActivity](BLAST)#0)
2024-05-20 13:53:24.109                                                              I  operator()(), mtkRenderCntDebug 1672, screenshot (com.linagora.android.teammail/com.linagora.android.tmail.MainActivity#0)
2024-05-20 13:53:24.126 DigestGenerator         com.miui.daemon                      D  digest=============com.linagora.android.teammailAbort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.()] Check failed: fml::jni::CheckException(env). 
                                                                                        '
                                                                                        
                                                                                        com.linagora.android.teammail
2024-05-20 13:53:24.306 ActivityManager         system_server                        I  Process com.linagora.android.teammail (pid 31688) has died: fg  TOP 
2024-05-20 13:53:24.307 ConnectivityService                                          D  releasing NetworkRequest [ REQUEST id=55760, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10490 RequestorUid: 10490 RequestorPkg: com.linagora.android.teammail UnderlyingNetworks: Null] ] (release request)
2024-05-20 13:53:24.307                                                              D  releasing NetworkRequest [ REQUEST id=55733, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10490 RequestorUid: 10490 RequestorPkg: com.linagora.android.teammail UnderlyingNetworks: Null] ] (release request)
2024-05-20 13:53:24.308 WindowManager                                                I  WIN DEATH: Window{ac10709 u0 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity}
2024-05-20 13:53:24.308 InputManager-JNI                                             W  Input channel object 'ac10709 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity (client)' was disposed without first being removed with the input manager!
2024-05-20 13:53:24.312 WindowManager                                                D  setParent old=ActivityRecord{884a3ab u0 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity t1893 f}},new=null,this window=Window{ac10709 u0 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity},callers=com.android.server.wm.WindowContainer.removeChild:620 com.android.server.wm.ActivityRecord.removeChild:4214 com.android.server.wm.ActivityRecord.removeChild:417 com.android.server.wm.WindowContainer.removeImmediately:672 com.android.server.wm.WindowState.removeImmediately:2533 com.android.server.wm.WindowState.removeIfPossible:2729 
2024-05-20 13:53:24.321 ProcessManager                                               D  skip restart com.linagora.android.teammail because this device is a lowmemory device!
2024-05-20 13:53:24.324 ActivityManager                                              W  Exception when unbinding service com.linagora.android.teammail/org.chromium.content.app.SandboxedProcessService0:2
                                                                                        android.os.DeadObjectException
                                                                                        	at android.os.BinderProxy.transactNative(Native Method)
                                                                                        	at android.os.BinderProxy.transact(BinderProxy.java:629)
                                                                                        	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1891)
                                                                                        	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:4513)
                                                                                        	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:4960)
                                                                                        	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:12182)
                                                                                        	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3124)
                                                                                        	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3260)
                                                                                        	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1485)
                                                                                        	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:314)
                                                                                        	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:743)
2024-05-20 13:53:24.331 BufferQueueDebug        surfaceflinger                       I  [com.linagora.android.teammail/com.linagora.android.tmail.MainActivity#0](this:0xb400007995fb38d0,id:-1,api:0,p:-1,c:944) onDestructor()
2024-05-20 13:53:24.333                                                              I  [SurfaceView[com.linagora.android.teammail/com.linagora.android.tmail.MainActivity](BLAST)#0](this:0xb4000079920b28d0,id:-1,api:0,p:-1,c:944) onDestructor()
2024-05-20 13:53:24.334 libPowerHal             ven...hardware.mtkpower@1.0-service  I  [perfNotifyAppState] pack:com.linagora.android.teammail, act:com.linagora.android.teammail, state:3, pid:31688, uid:10490, fps:-1
2024-05-20 13:53:24.334                                                              I  [perfNotifyAppState] pack:com.linagora.android.teammail, pid:31688, STATE_DEAD
2024-05-20 13:53:24.337 WindowManager           system_server                        D  setParent old=Task{b99fa08 #1893 type=standard A=10490:com.linagora.android.teammail U=0 visible=false mode=fullscreen translucent=true sz=0},new=null,this window=ActivityRecord{884a3ab u0 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity t1893 f}},callers=com.android.server.wm.WindowContainer.removeChild:620 com.android.server.wm.Task.removeChild:1896 com.android.server.wm.Task.removeChild:1877 com.android.server.wm.WindowContainer.removeImmediately:672 com.android.server.wm.WindowToken.removeImmediately:363 com.android.server.wm.ActivityRecord.removeImmediately:4031 
2024-05-20 13:53:24.339                                                              D  setParent old=DefaultTaskDisplayArea@140406872,new=null,this window=Task{b99fa08 #1893 type=standard A=10490:com.linagora.android.teammail U=0 visible=true mode=fullscreen translucent=true sz=0},callers=com.android.server.wm.WindowContainer.removeChild:620 com.android.server.wm.TaskDisplayArea.removeChildTask:402 com.android.server.wm.TaskDisplayArea.removeChild:393 com.android.server.wm.WindowContainer.removeImmediately:672 com.android.server.wm.Task.removeImmediately:3695 com.android.server.wm.Task.removeIfPossible:1086 
2024-05-20 13:53:24.351 AppObserver             com.miui.home                        D  ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10085, mForegroundPid=2418, mLastForegroundPackageName='com.linagora.android.teammail', mLastForegroundUid=10490, mLastForegroundPid=31688, mMultiWindowForegroundPackageName='com.miui.home', mMultiWindowForegroundUid=10085, mFlags=0}
2024-05-20 13:53:24.351 ProcessMonitor          com.miui.securitycenter.remote       I  onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10085, mForegroundPid=2418, mLastForegroundPackageName='com.linagora.android.teammail', mLastForegroundUid=10490, mLastForegroundPid=31688, mMultiWindowForegroundPackageName='com.miui.home', mMultiWindowForegroundUid=10085, mFlags=0}
2024-05-20 13:53:24.353 PerfEngineController    com.miui.powerkeeper                 D  ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10085, mForegroundPid=2418, mLastForegroundPackageName='com.linagora.android.teammail', mLastForegroundUid=10490, mLastForegroundPid=31688, mMultiWindowForegroundPackageName='com.miui.home', mMultiWindowForegroundUid=10085, mFlags=0}
2024-05-20 13:53:24.357 libPowerHal             ven...hardware.mtkpower@1.0-service  I  [perfNotifyAppState] pack:com.linagora.android.teammail, act:com.linagora.android.teammail, state:3, pid:2885, uid:99542, fps:-1
2024-05-20 13:53:24.357                                                              I  [perfNotifyAppState] pack:com.linagora.android.teammail, pid:2885, STATE_DEAD
2024-05-20 13:53:24.360 ThermalInfoCollector    com.miui.powerkeeper                 I  collectForgroundAppsInfo: com.linagora.android.teammail
2024-05-20 13:53:24.377 ProcessMonitor          com.miui.msa.global                  I  onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10085, mForegroundPid=2418, mLastForegroundPackageName='com.linagora.android.teammail', mLastForegroundUid=10490, mLastForegroundPid=31688, mMultiWindowForegroundPackageName='com.miui.home', mMultiWindowForegroundUid=10085, mFlags=0}
2024-05-20 13:53:24.386 GST                     com.xiaomi.joyose                    I  forePkg: com.miui.home, preForePkg: com.linagora.android.teammail
2024-05-20 13:53:24.591 ActivityTaskManager     system_server                        W  Activity top resumed state loss timeout for ActivityRecord{884a3ab u0 com.linagora.android.teammail/com.linagora.android.tmail.MainActivity t-1 f}}
2024-05-20 13:53:24.592 PowerHalWrapper                                              I  amsBoostNotify pid:2418,activity:com.miui.home.launcher.Launcher, package:com.miui.home, mProcessCreatePackcom.linagora.android.teammail 
2024-05-20 13:53:24.594 mtkpower@impl           ven...hardware.mtkpower@1.0-service  I  [notifyAppState] pc:0, com.linagora.android.teammail => com.miui.home

```
</details>

Flutter issue: 
- https://github.com/flutter/flutter/issues/112542
- https://github.com/flutter/flutter/issues/125090
